excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://devblog.novatrox.se
title: Novatrox Dev Blog
email: 
author: Novatrox
description: 
paginate: 5
google_analytics: 

authors:
  tkallsen:
    display_name: Tomas Källsen

  mporttila:
    display_name: Mikael Porttila
    twitter: ecodot

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true
