excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://Novatrox.github.io
title: Novatrox Dev Blog
email: 
author: Novatrox
description: My awesome new site
paginate: 3
google_analytics: 